#---------------------------------------------
apiVersion: v1
kind: AccessPolicyList
requestNumber: 123
generated: 2025-06-06T00:00:00Z
---

id: 1
system: databricks
environment:
- dev
- qas
- prd
object:
  type: VIEW
  name:
    - schema.view1
    - schema.view2
principal:
  type: user_group
  name: ELSA-DLDB-{env}-AR-DEVELOPER
expiry: 2025-12-31T23:59:59Z
---

id: 2
system: databricks
environment:
- dev
- qas
- prd
object:
  type: SCHEMA
  name: bt_masterdata
principal:
  type: user
  name:
    - alex.b@bayer.com
    - naghman.w@bayer.com
privilege: SELECT
