name: Validate YAML on PR

on:
  pull_request:
    branches:
      - main            # Only run if PR targets the 'main' branch
      # - dev           # You can add other target branches too
    paths:
      - 'D1LH-PLAT-ACCESS-Infrastructure/configs/requests/*.yml'

jobs:
  validate-yaml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pydantic PyYAML

      - name: Get changed YAML files
        id: changed
        run: |
          echo "files=$(git diff --name-only origin/${{ github.base_ref }} | grep '\.yml$' | tr '\n' ' ')" >> "$GITHUB_OUTPUT"

      - name: Validate YAML files
        run: |
          python D1LH-PLAT-ACCESS-Infrastructure/notebooks/YAML_checker.py ${{ steps.changed.outputs.files }}
        if: steps.changed.outputs.files != ''
